### ISSUE TITLE
Crash when test example project

### ISSUE THREAD

**Issue by ban9ban3** [tispr/tispr-card-stack#19]
![screen shot 2017-05-11 at 10 00 38 am](https://cloud.githubusercontent.com/assets/10986151/25930505/d647beec-3630-11e7-9153-e9cf2aeb7578.png)
I got this error when run the example, please check!
Thanks

**Comment by pradeepb28** [comment]
You can actually unwrap the value of the cell property and test it. It shouldn't crash.

Regards,
Pradeep

**Comment by RoshaniDias** [comment]
Hi For me also its crashing here. @ban9ban3 How did you unwrap it?
![screen shot 2017-07-30 at 11 10 06 pm](https://user-images.githubusercontent.com/13362132/28755621-b260f8b4-757c-11e7-8ca2-079f63aa65e2.png)

**Comment by bannn-1018** [comment]
you can unwap by "if let"
ex:
`if let cell = collectionView?.cellForItem(at: indexPath) {
                    finishedDragging(cell)
                }`
