### ISSUE TITLE
Swipe Card in single Direction

### ISSUE THREAD

**Issue by Abhishek-NickelFox** [tispr/tispr-card-stack#20]
i need swipe Card in down direction only. How can i achieve that?
Also it is crashing when swipe up direction: error: **fatal error: Can't form Range with upperBound < lowerBound**

**Comment by AbhishekNFX** [comment]
let newCenterX = initialCellCenter!.x Chnages and worked

**Comment by Abhishek-NickelFox** [comment]
@Pitsko : Please Help

**Comment by Pitsko** [comment]
I will try to look in this issue in a few next days

**Comment by Pitsko** [comment]
Crash is fixed in 1.0.1

So you need drag and drop + swift just to down direction
@AbhishekNFX please confirm if you still need it ?, sorry for big delay
