### ISSUE TITLE
Remove Card from the stack

### ISSUE THREAD

**Issue by RoshaniDias** [tispr/tispr-card-stack#21]
I want to do a delete function with this. Can you guide me how to do that. I did reloading the view after remove an object from the stack but it's crashing for me.

After I go to the next view and perform the delete action. then when come back my stack should be refreshed. In viewdidappear() I did this
`

      if(dm.cardshouldRefresh || isFirsttimeLoad)
        {
            
            com.showProgress()
            
            self.getAuthorizations() { (status) in
                
                self.dm.cardshouldRefresh=false
                self.isFirsttimeLoad=false
                self.com.removeProgress()
                if (status)
                {
                    self.setupCardView()

                }

            }
        }
        
        else
        {
            print(arrayAuthorization)
            
        }   
    }
    
    func makecollectionViewEmpty()
    {
        arrayAuthorization.removeAll()
        vwBtnPanelBottom.removeFromSuperview()
        self.collectionView?.reloadData()
    }
`

**Comment by Pitsko** [comment]
@RoshaniDias this ticket was opened one month ago, can you confirm that you still need it ?
Sorry for delay
