### ISSUE TITLE
cannot add header with TisprCard

### ISSUE THREAD

**Issue by benMohamed** [tispr/tispr-card-stack#23]
i can't add a custom header with your sdk !!!

**Comment by Pitsko** [comment]
Can you provide more details what you are trying to do ?

**Comment by benMohamed** [comment]
these 2 delegate functions are not called  
* func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, referenceSizeForHeaderInSection section: Int) -> CGSize
* func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView
