### ISSUE TITLE
Swipe Gestures on iOS9 / Swift 2

### ISSUE THREAD

**Issue by morgz** [tispr/tispr-card-stack#7]
I've had to disable the swipe gestures as I've found them not to redraw the card stack properly. For example, swiping down a card can result in it disappearing. If I then drag up the 'invisible' card it suddenly appears.

I'm not having any problems with the Pan gesture.

**Comment by Pitsko** [comment]
Thank you for reporting this issue, we will address it as soon as possible

**Comment by weyert** [comment]
Yes, I am experiencing a similar issue at the moment.

**Comment by Pitsko** [comment]
fixed in https://github.com/tispr/tispr-card-stack/pull/10
