### ISSUE TITLE
Could not cast value of type 'UICollectionViewFlowLayout' to 'Swish.TisprCardStackViewLayout'

### ISSUE THREAD

**Issue by briannadoubt** [tispr/tispr-card-stack#8]
The error Could not cast value of type 'UICollectionViewFlowLayout' to 'Swish.TisprCardStackViewLayout' appears each time I try and build this. I just dropped the three files into my project. Any ideas anyone?

**Comment by Pitsko** [comment]
Did you put class TisprCardStackViewLayout as your collectionViewLayout in storyboard or code ?
